name: Continuous Integration Workflow

on: [push]

env:
  CACHE_VERSION: 9c3bfa173ea0aca1f9939f8896feb4a5

jobs:
  core:
    name: Core Tests
    runs-on: self-hosted
    container: smartcontract/builder:1.0.34
    env:
      DATABASE_URL: postgres://chainlink@postgres:5432/chainlink_test?sslmode=disable
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Postgres user
        uses: docker://postgres
        with:
          args: psql -v ON_ERROR_STOP=1 --username postgres -h postgres -c "CREATE USER chainlink NOSUPERUSER CREATEDB;"
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: yarn-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ env.CACHE_VERSION }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Cache Go vendor packages
        uses: actions/cache@v1
        with:
          path: /go/pkg/mod
          key: go-mod-${{ env.CACHE_VERSION }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-${{ env.CACHE_VERSION }}
      - name: Download Go vendor packages
        run: go mod download
      - name: Set up Yarn for Contracts
        run: yarn setup:contracts
      - name: Setup DB
        run: go run ./core local db preparetest
      - name: Run tests
        run: ./tools/bin/go_core_tests

  rust:
    name: Rust
    runs-on: ubuntu-latest
    container:
      image: smartcontract/builder:1.0.34
      env:
        CARGO_HOME: /root/.cargo
        RUSTUP_HOME: /root/.rustup
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run Rust test
        run: ./tools/ci/rust_test

  integration:
    name: Integration tests
    runs-on: self-hosted
    strategy:
      matrix:
        test: ['test', 'test:ts']
        geth: [true, false]
    env:
      GETH_MODE: ${{ matrix.geth }}
      CI: true
      CHAINLINK_DB_NAME: postgres
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run tests
        run: cd ./tools/docker && timeout --foreground 1200s ./compose ${{ matrix.test }}
      - name: Store logs artifacts
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: ./tools/docker/logs

  solidity:
    name: Solidity
    runs-on: self-hosted
    container: smartcontract/builder:1.0.34
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: yarn-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ env.CACHE_VERSION }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run tests
        run: ./tools/ci/solidity_test
      - name: Store logs artifacts
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: ./integration/logs

  styleguide:
    name: Styleguide
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.34
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: yarn-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ env.CACHE_VERSION }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run styleguide tests
        run: yarn workspace @chainlink/styleguide test

  json-api-client:
    name: JSON API client
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.34
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: yarn-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ env.CACHE_VERSION }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run JSON API client tests
        run: yarn workspace @chainlink/json-api-client test

  operator-ui:
    name: Operator UI
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.34
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: yarn-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ env.CACHE_VERSION }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run Operator UI tests
        run: ./tools/ci/operator_ui_test
      - name: Store logs artifacts
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: ./integration/logs

  explorer:
    name: Explorer
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.34
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: explorer_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      TYPEORM_NAME: ci-gh
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: yarn-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ env.CACHE_VERSION }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run setup
        run: yarn workspace @chainlink/explorer setup
      - name: Run Yarn migrations
        run: yarn workspace @chainlink/explorer test:migration:run
      - name: Run Server Tests
        run: yarn workspace @chainlink/explorer test:ci
      - name: Run Client dependency setup
        run: yarn workspace @chainlink/explorer-client setup
      - name: Run Client tests
        run: yarn workspace @chainlink/explorer-client test:ci
      - name: Store logs artifacts
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: ./integration/logs

  feeds:
    name: Feeds
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.34
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: yarn-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ env.CACHE_VERSION }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run Feeds setup
        run: yarn workspace @chainlink/feeds setup
      - name: Run Feeds tests
        run: yarn workspace @chainlink/feeds test
        env:
          CI: true

  reportcoverage:
    name: Report test coverage
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.34
    needs: [core, solidity, operator-ui, rust, explorer]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Init GCloud
        run: ./tools/ci/init_gcloud
      - name: Run coverage report
        run: ./tools/ci/report_coverage

  check_if_rebase_needed:
    name: Check if rebase needed
    runs-on: ubuntu-latest
    container: alpine/git
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          # Default fetch depth of 1 prevents us from knowing if HEAD of develop
          # branch is present in current branch
          fetch-depth: 1000
      - name: Check if rebase is needed
        run: tools/bin/check_if_rebase_needed

  lint:
    name: Yarn lint
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.34
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: yarn-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ env.CACHE_VERSION }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run Yarn lint
        run: yarn lint

  prepublish_npm:
    name: Prepublish NPM
    runs-on: self-hosted
    container: smartcontract/builder:1.0.34
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: yarn-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ env.CACHE_VERSION }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run prepublish NPM test
        run: ./tools/ci/prepublish_npm_test

  build-chainlink:
    name: Build chainlink image
    runs-on: self-hosted
    needs:
      - core
      - geth
      - parity
      - styleguide
      - json-api-client
      - operator-ui
      - rust
    strategy:
      matrix:
        dockerfile: [core/chainlink.Dockerfile, core/chainlink-sgx.Dockerfile]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: '${{ secrets.AWS_DEFAULT_REGION }}'
          role-to-assume: '${{ secrets.AWS_ROLE_TO_ASSUME }}'
          role-duration-seconds: 1200
          role-session-name: 'temp-session'
          role-skip-session-tagging: true
      - name: Docker login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      # https://github.com/docker/build-push-action/issues/20
      - name: Get ecr password
        id: get-ecr-password
        run: |
          aws ecr get-login-password \
          | {
            read PASSWORD
            echo "::add-mask::$PASSWORD"
            echo "::set-output name=password::$PASSWORD"
            }
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: ${{ secrets.ECR_REPO }}
          username: AWS # temporary
          password: ${{ steps.get-ecr-password.outputs.password }} # temporary
          dockerfile: ${{ matrix.dockerfile }}
          build_args: COMMIT_SHA=${{ github.sha }},SGX_SIMULATION=${{ contains(matrix.dockerfile, 'sgx') }},ENVIRONMENT=release
          tags: githubactions
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true
          push: false
